name: memeland
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: 'Memeland, donde se da libertad al pensamiento y se habla de todo lo que quizás piensas y no dices'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c110d'
    - '#f2f7f2'
    - '#79c0d8'
    - '#497ea2'
    - '#c02831'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
